# Generated by Django 4.2.18 on 2025-02-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_on',
        ),
    ]
