# Generated by Django 4.2.18 on 2025-02-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='ingredients'),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(default='ingredients'),
        ),
    ]
